#.travis.yml

language: node_js
node_js:
- "stable"

before_install:
- 'nvm install-latest-npm'

cache:
  directories:
  - node_modules

branches:
  only:
  - master

before_script:
- npm install -g firebase-tools
- npm install

script:
- npm run build

after_success:
- firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change